# The title of your website
title: Jana El Husseiny Lab

# The URL of your site (make sure it has the / at the end)
baseURL: 'https://jana-elhusseiny.github.io/'

# This is the "brain" that connects to Hugo Blox
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
