title: Jana El Husseiny Lab
baseURL: 'https://janaelhusseiny-lab.github.io/'

# Edit the following for your own site
copyright: '© {year} Jana El Husseiny'

# Module System
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
